CONCURSO_INTERNO_PERSONAL/Controllers/ContratacionPersonalController.cs
using CONCURSO_INTERNO_PERSONAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace CONCURSO_INTERNO_PERSONAL.Controllers
{
    public class ContratacionPersonalController : Controller
    {
        private readonly SmvConcursoInternoContext _SmvContext;
        private readonly IConverter _converter;

        public ContratacionPersonalController(SmvConcursoInternoContext context, IConverter converter)
        {
            _SmvContext = context;
            _converter = converter;
        }

        [Authorize(Roles = "jefeRecursosHumanos, admin")]
        [HttpGet]
        public IActionResult TablaContratPersonal()
        {
            List<Personal> lista = _SmvContext.Personals.Include(pt => pt.oPuesto).ToList();
            return View(lista);
        }
        [HttpGet]
        public IActionResult VistaPDF()
        {
            List<Personal> lista = _SmvContext.Personals.Include(p => p.oPuesto).ToList();
            return View(lista);
        }
        [Authorize(Roles = "jefeRecursosHumanos, admin")]
        [HttpGet]
        public IActionResult MostrarPDFenPagina()
        {
            string pagina_actual = HttpContext.Request.Path;
            string url_pagina = HttpContext.Request.GetEncodedUrl();
            url_pagina = url_pagina.Replace(pagina_actual, "");
            url_pagina = $"{url_pagina}/ContratacionPersonal/VistaPDF";

            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings()
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait
                },
                Objects = {
                    new  ObjectSettings(){
                        Page = url_pagina
                    }
                }
            };
            var archivoPDF = _converter.Convert(pdf);

            return File(archivoPDF, "application/pdf");
        }
        [Authorize(Roles = "jefeRecursosHumanos, admin")]
        
        public IActionResult Eliminar(int Idpersonal)
        {
            try
            {
                Personal oPersonal = _SmvContext.Personals.Find(Idpersonal);

                if (oPersonal == null)
                {
                    return NotFound();
                }

                _SmvContext.Personals.Remove(oPersonal);
                _SmvContext.SaveChanges();

                return Json(new { success = true, message = "Eliminación exitosa" });
            }
            catch
            {
                return Json(new { success = false, message = "Error al intentar eliminar al postulante." });
            }
        }

    }
}

CONCURSO_INTERNO_PERSONAL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using CONCURSO_INTERNO_PERSONAL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CONCURSO_INTERNO_PERSONAL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SmvConcursoInternoContext _DBcontext;

        public HomeController(ILogger<HomeController> logger, SmvConcursoInternoContext context)
        {
            _logger = logger;
            _DBcontext = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CONCURSO_INTERNO_PERSONAL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

    bool tieneAccesoPerfilPuesto = User.IsInRole("profesionalPerfil") || User.IsInRole("admin");
    bool tieneAccesoPruebaConocimiento = User.IsInRole("encargadoSeleccionPersonal") || User.IsInRole("admin");
    bool tieneAccesoSeleccionPersonal = User.IsInRole("comiteSeleccion") || User.IsInRole("saoga") || User.IsInRole("admin");
    bool tieneAccesoContratacion = User.IsInRole("jefeRecursosHumanos") || User.IsInRole("admin");
    bool tieneAccesoAdministrarPresupuesto = User.IsInRole("jefeRecursosHumanos") || User.IsInRole("analistaPresupuestal") || User.IsInRole("admin");
    bool tieneAccesoValidarPresupuesto = User.IsInRole("jefeFinanzas") || User.IsInRole("admin");
}
<link rel="stylesheet" href="~/css/Index_Interfaz.css" />
<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,300;1,900&display=swap" rel="stylesheet">
<div class=" index-container row row-cols-1 row-cols-md-3 g-5 align-items-center justify-content-center  pb-5">
        
        <div class=" tarjeta_interfaz @(tieneAccesoPerfilPuesto ? "" : "inactive-card")">
            <a  style="text-decoration:none" asp-action="Perfil_Puest_detalle" asp-controller="PerfilPuesto">
            
               
            <div class="tarjeta-text">
               <h5 class="">Perfil de <br /> Puesto</h5>
               
               
               <p class="">Resp: Profesional Perfil de Puesto</p>
              
            </div>

            <div class="tarjeta_img"> 
                <img src="~/imgCU/perfil-Puesto.webp" class="" alt="imagen Perfil Puesto">
            
            </div>
            </a>
        </div>

    <div class=" tarjeta_interfaz @(tieneAccesoPruebaConocimiento ? "" : "inactive-card" )">
            <a style="text-decoration:none" asp-action="Prueba_index" asp-controller="Prueba">

            <div class="tarjeta-text">
                <h5 class=""> Prueba <br /> Conocimiento</h5>


                <p class="">Resp: Encargado de RR.HH.</p>

            </div>

            <div class="tarjeta_img">
                <img src="~/imgCU/prueba-Conocimiento.webp" class="" alt="imagen Prueba">

            </div>
        </a>
        </div>

    <div class="tarjeta_interfaz @(tieneAccesoSeleccionPersonal ? "" : "inactive-card")">
        <a style="text-decoration:none" asp-action="AdministrarPersonal" asp-controller="SeleccionPersonal">

            <div class="tarjeta-text">
                <h5 class=""> Selección de  <br />  Personal </h5>


                <p class="">Resp: Comité Selección y SAOGA</p>

            </div>

            <div class="tarjeta_img">
                <img src="~/imgCU/seleccion-Personal.webp" class="card-img-top" alt="imagen seleccion Personal">

            </div>
        </a>
        </div>

    <div class="tarjeta_interfaz @(tieneAccesoContratacion ? "" : "inactive-card")">
            <a style="text-decoration:none" asp-action="TablaContratPersonal" asp-controller="ContratacionPersonal">

                <div class="tarjeta-text">
                    <h5 class=""> Contratación de  <br />  Personales   </h5>


                    <p class="">Resp: Jefe de RR.HH.</p>

                </div>

                <div class="tarjeta_img">
                    <img src="~/imgCU/contratacion1.webp" class="card-img-top" alt="imagen Contratacion">

                </div>
            </a>
        </div>

    <div class="tarjeta_interfaz @(tieneAccesoAdministrarPresupuesto ? "" : "inactive-card")">
            <a style="text-decoration:none" asp-action="SolicitarSueldo" asp-controller="Presupuesto">
            <div class="tarjeta-text">
                <h5 class=""> Administración de <br />   Presupuesto     </h5>


                <p class="">Resp: Jefe de RR.HH. y Analista</p>

            </div>

            <div class="tarjeta_img">
                <img src="~/imgCU/administrar-Presupuesto.webp" class="card-img-top" alt="imagen Administrar Presupuesto">

            </div>
        </a>
        </div>

    <div class="tarjeta_interfaz @(tieneAccesoValidarPresupuesto ? "" : "inactive-card")">
            <a style="text-decoration:none" asp-action="Solicitud_Presupuesto" asp-controller="Presupuesto">
            <div class="tarjeta-text">
                <h5 class=""> Validación para <br />   Presupuesto      </h5>


                <p class="">Resp: Jefe de Finanzas</p>

            </div>

            <div class="tarjeta_img">
                <img src="~/imgCU/validacion-Presupuesto.webp" class="card-img-top" alt="Imagen Validacion Presupuesto">

            </div>
        </a>
    </div>
    
</div>